global using ActiveDiabetesAssistant.DAL.Interfaces;
global using ActiveDiabetesAssistant.DAL.Interfaces.Base;
global using ActiveDiabetesAssistant.DAL.SQL.Base;
global using ActiveDiabetesAssistant.DAL.SQL.Contexts;
global using GMD.PrivateMessenger.DAL.Entities;
global using GMD.PrivateMessenger.DAL.Entities.Wrappers;
global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using System.Reflection;